# Generated by Django 4.0.3 on 2022-10-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_game_rating_gamereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamereview',
            old_name='book',
            new_name='game',
        ),
    ]
