# Generated by Django 4.1.4 on 2023-01-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_alter_orderservice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.order'),
        ),
    ]
