"""a

Revision ID: c3bdf7f777cc
Revises: 
Create Date: 2023-08-11 10:38:07.336755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3bdf7f777cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pavadinimas', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('darbuotojas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vardas', sa.String(), nullable=True),
    sa.Column('pavarde', sa.String(), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('darbuotojas')
    op.drop_table('departamentas')
    # ### end Alembic commands ###
