# Generated by Django 4.1.4 on 2023-01-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilio_modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Input book's genre (for example: detective)", max_length=200, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(help_text="Car's licence plate", max_length=10, verbose_name='Licence plate')),
                ('vin_code', models.CharField(help_text="Car's vin code", max_length=20, verbose_name='Vin code')),
                ('client', models.CharField(help_text="Client's name", max_length=50, verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Car make', max_length=20, verbose_name='Make')),
                ('model', models.CharField(help_text='Car model', max_length=20, verbose_name='Model')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text="Order's date", verbose_name='Date')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.car')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the service', max_length=50, verbose_name='Title')),
                ('price', models.FloatField(help_text='The price of the service', verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity of the service', verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.service')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.carmake'),
        ),
    ]
