# Generated by Django 4.1.4 on 2023-01-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Automobilio_modelis',
        ),
    ]
