# Generated by Django 4.1.4 on 2023-01-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_delete_automobilio_modelis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='carmake',
            options={'verbose_name': 'Car make', 'verbose_name_plural': 'Car makes'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderservice',
            options={'verbose_name': 'Order service', 'verbose_name_plural': 'Order services'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'Ordered'), ('i', 'In progress'), ('d', 'Done')], default='o', help_text='Status', max_length=1),
        ),
    ]
