# Generated by Django 4.0.3 on 2022-10-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_game_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.IntegerField(help_text='Žaidimo įvertinimas', null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Pavadinimas'),
        ),
    ]
