# Generated by Django 4.0.3 on 2022-10-26 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_rename_book_gamereview_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereview',
            name='rating',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(help_text='Select genres for games', to='reviews.genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(help_text='Game description', max_length=1000, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gamereview',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='Review Content'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Select or create game genre (FPS)', max_length=200, verbose_name='TName'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
