"""pradzia

Revision ID: 8c474bae019b
Revises: 
Create Date: 2023-08-09 13:37:49.380182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c474bae019b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('darbuotojai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vardas', sa.String(length=80), nullable=False),
    sa.Column('pavarde', sa.String(length=120), nullable=False),
    sa.Column('el_pastas', sa.String(length=40), nullable=False),
    sa.Column('tel_numeris', sa.String(length=40), nullable=False),
    sa.Column('alga', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alga'),
    sa.UniqueConstraint('el_pastas'),
    sa.UniqueConstraint('tel_numeris')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('darbuotojai')
    # ### end Alembic commands ###
