"""added phone column

Revision ID: cf61a1a0baba
Revises: 
Create Date: 2023-01-07 18:38:49.866745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf61a1a0baba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('phone', sa.String(length=40), nullable=True))
        batch_op.create_unique_constraint('unique_phone', ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('unique_phone', type_='unique')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
