# Generated by Django 4.1.4 on 2023-01-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0005_alter_orderservice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='car_images', verbose_name='Image'),
        ),
    ]
